### ISSUE TITLE
Not working for me, not sure why

### ISSUE THREAD

**Issue by jacobshare** [iseulde/wp-front-end-editor#106]
I'm on WordPress 3.9.1 multisite-enabled.

After installing and activating the plugin in my development environment-

I enabled the WordPress Admin Toolbar. When I visit a post, if I click the Edit Post menu item, the post just refreshes and nothing happens. It's not in edit mode, and I'm not sent to the backend Edit Post page either.

I even tried adding an edit link to my theme (http://codex.wordpress.org/Function_Reference/edit_post_link), but clicking that link has the same effect: the post refreshes but no edit mode. Yet if I disable the plugin, clicking that edit link sends me to the backend.

Maybe my custom theme isn't compatible?

But then I enabled the Twenty Fourteen theme. Clicking Edit Post in the Toolbar just refreshes the page - like with my theme - and I'd be surprised if this latest, greatest officially standard theme was incompatible. Assuming that's not the case, maybe this problem isn't theme-related.

Any other ideas?

**Comment by iseulde** [comment]
Editor changed a lot, so closing. Feel free to reopen if it's still an issue.
