### ISSUE TITLE
0.X recommendation 3: Change Wording of "Just write..."

### ISSUE THREAD

**Issue by Telstar1980** [iseulde/wp-front-end-editor#136]
Again this is expecting a little guess-work from a new user, so would be better if the statement included what the author needs to do: e.g. "Just write… To format, just highlight the area you want to change…"

This could be a re-wording, or you could have a pop up box that appears to guide the writer (actually that could be the way forward for all of these things I'm highlighting...)

**Comment by iseulde** [comment]
I'm thinking to remove the text and add a dotted line around empty content. This would only be visible in edit mode (not view mode), when the content is empty and when the area is not focussed. Thoughts are welcome.
