### ISSUE TITLE
Cannot see or select audio or video block items

### ISSUE THREAD

**Issue by davidsdesk** [iseulde/wp-front-end-editor#154]
After a video or audio file is inserted into a page there is no way to return and edit or delete the item using the front-end editor. The audio and video block items don't "occupy" any space and cannot be seen or selected after inserting.

Running WP Front End Editor 1.0 (8/21/14) and WP 4.0-RC1.

**Comment by iseulde** [comment]
Should all be fixed.

**Comment by iseulde** [comment]
(Feel free to reopen though.)
