### ISSUE TITLE
Query Monitor throws this notice on PHP 5.6

### ISSUE THREAD

**Issue by GabrielGil** [iseulde/wp-front-end-editor#157]
![screen shot 2014-09-05 at 15 27 38](https://cloud.githubusercontent.com/assets/961534/4165269/77a3fa74-3500-11e4-9c8c-aa284c315288.png)

**Comment by jambox** [comment]
I'm getting the same thing here with PHP 5.4. FYI, It's not a "Query Monitor" notice, but a standard PHP notice being displayed via your Query Monitor plugin (I'd revise the name of the issue to clarify there's a PHP warning thrown by `post_tags_meta_box()`).

Anyway, I just dipped into the code and from what I can gather it looks like @iseulde was working on allowing tag editing but stopped short of finishing the function. (If the tag edit system is supposed to be working, I can't see it. Can you, @GabrielGil ?). There's no button on the FEE toolbar but the tag modal is in the DOM and you can still toggle it by running `$('.fee-post_tag-modal').modal('show')` in the console.

On [L634 of class-fee.php](https://github.com/iseulde/wp-front-end-editor/blob/master/src/class-fee.php#L634) there are two args passed, the `$post` obj and then an `args` array with a `taxonomy` key...the function it calls ( `post_tags_meta_box()`) is expecting two params : `$post` and `$box`, where `$box['title']` is set. As far as I can see there's no place where a `$box` obj is being passed, and especially not one with a `title` key. Can anyone confirm this?

Looks like there should be some sort of conditional testing the presence of that key and/or an additional param passed in that `args` array...

**Comment by christianwach** [comment]
> As far as I can see there's no place where a $box obj is being passed, and especially not one with a title key. Can anyone confirm this?

@jambox yes, confirmed here. Although it should be said that the `array` *is* the `$box` definition. At minimum, that line should read:

`call_user_func( $taxonomy->meta_box_cb, $post, array( 'title' => $taxonomy->labels->name, 'args' => array( 'taxonomy' => $tax_name ) ) );`

However, that doesn't solve the fact that there's no way to get the Tags box to appear.

**Comment by iseulde** [comment]
I've removed this for now.
