### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by Danny-weebo** [iseulde/wp-front-end-editor#162]
I'm using 1.0.0-beta1 and seems like the plugin throw the error 'Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined'
any idea what could make this happen and how can I fix this ?

thanks

**Comment by rotexhawk** [comment]
I am getting the same error. Both with Chrome and firefox. The strange thing is that this problem only occurs on the homepage. The plugin works perfect on the internal pages.

**Comment by iseulde** [comment]
Should be gone. Feel free to reopen if this is still an issue.
