### ISSUE TITLE
Gist oEmbed Integration not working

### ISSUE THREAD

**Issue by GabrielGil** [iseulde/wp-front-end-editor#164]
When I paste a Gist on the admin editing page, it works perfectly. However, in the front it is saved, but not shown up till I save and refresh.

**Comment by iseulde** [comment]
Should be gone after 69e616e3411013c1f8553bff5519a9b81370c873 and 8f136aa01f1c5782cda74056686ee0ee3aeb9394. Please reopen if it's still an issue, thanks!
