### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by bigkev1983** [iseulde/wp-front-end-editor#166]
Hi Avryl

Great work on the editor, now I've used it with other themes I see where it's headed.

So having tested it out properly on some different themes, I've realised there's an incompatibility with themes by the Qode developer. Here's a link to one I'm using at the moment so you can repeat the problem locally. https://dl.dropboxusercontent.com/u/3353568/bridge.zip

**Comment by iseulde** [comment]
The editor changed a lot, "add block" is gone. Feel free to create an issue if there are still problems with this master branch.
