### ISSUE TITLE
public + Featured Content

### ISSUE THREAD

**Issue by opek7** [iseulde/wp-front-end-editor#185]
on WP4 + Twenty Fourteen 1.2 + wp front end editor 1.0.0-beta1.1
when i edit a post on frontend not have plus buttom for insert image/txt or other, and when save the post (on keyboard or upgrade botton) the post have in automatic in "Featured Content" propriety without setting it.
i tested it with 4 theme. same problem.

NOTE: i use OSX 10.9.5 maverick but in OSX 10.6.8 the PLUS Buttom work fine

**Comment by iseulde** [comment]
The insert button is gone. Please open a new issue if there are remaining problems.
