### ISSUE TITLE
Cannot search/manually find post when linking previous post

### ISSUE THREAD

**Issue by yevmail** [iseulde/wp-front-end-editor#195]
Two related issues:

1) When inserting a link to the previous post, clicking on the "or link to existing content" removes the list with the previous posts completely, making it impossible to link any previous post. I need go back to the admin and fix it there.

2) When linking to previous post, the search field is missing.

Thanks

![image](https://dl.dropboxusercontent.com/s/lctw17b7fr5mdr7/2014-11-20%20at%203.18%20PM%20%281%29.png)

**Comment by iseulde** [comment]
This is removed for now, but should maybe be added back in the future.
