### ISSUE TITLE
Error when taking over on front-end

### ISSUE THREAD

**Issue by asoretmadolell** [iseulde/wp-front-end-editor#199]
Hello! First of all, congratulations for your plugin. Very handy, and deserves to be updated! I've just come across a small error that I don't know what's causing it. If a different user is editing the same page you want to edit on the frontend, it will ask you if you want to take over. If you do, it will try to redirect you to a url such as "http://yoursite.com/page/?get-post-lock=1#fee-edit-link", and the browser will crash saying something like "the page is not redirecting properly". It's not really important, because if you hit "back" on your browser, everything will be well, but I thought you might wanted to know!

**Comment by iseulde** [comment]
Post locking is gone for now, will look into this again later.
