### ISSUE TITLE
'wptexturize' can cause trouble

### ISSUE THREAD

**Issue by asoretmadolell** [iseulde/wp-front-end-editor#200]
Hello again, friend! I've come up with a small problem that can be easily solved. Long story short, I'm using a plugin called "Easy Table" and it sometimes needs double quotes, which get replaced when 'wptexturize' does its thing on the frontend editor. I was afraid that could cause trouble to my client, and so I decided to comment line #377 on "class-fee.php" because adding "remove_filter( 'fee_content', 'wptexturize' );" simply didn't do the trick. It could be great to have the option to disable it :D

**Comment by iseulde** [comment]
Yeah I think it might be better to remove this, until there's some kind of JS version. See #142.
