### ISSUE TITLE
Cannot indent

### ISSUE THREAD

**Issue by dnaber-de** [iseulde/wp-front-end-editor#201]
On the header image of the plugin page https://wordpress.org/plugins/wp-front-end-editor/ one can see an admin bar with editor buttons. I think I used this plugin before and I remember this toolbar. 

Now with WP 4.0.1 and FEE 1.0.0.-beta1.2 the toolbar is gone. Is that a bug or a feature? And if so, how can one change, for example, indentation?

**Comment by iseulde** [comment]
Everything will be inline. We'll try to find alternatives for all buttons. We could use the tab for indentation.

**Comment by dnaber-de** [comment]
Well, the question was on what happened to the UI element. »Cannot Indent« doesn't explain the question. However, thanks for the explanation.
