### ISSUE TITLE
Youtube video not shown in FEE

### ISSUE THREAD

**Issue by Krielkip** [iseulde/wp-front-end-editor#202]
When using the FEE on the content and loading a youtube video, the system breaks and JS gives back that insert is not a node. (mce-view.js) (1.0.0 beta)

In setContent add before if (_.isSting(insert)) { 
```
if (_.isObject(insert)) {
					$.each( insert, function( key, val ) {
						if ( key === 'body' ) {
							insert = val;
							return;
						}
					});
				}
```

Problem is that the insert of the youtube video is a object and not a string. So there was no element created.

**Comment by laurgaut** [comment]
I have the same problem in mce-view.js file

**Comment by Krielkip** [comment]
@laurgaut No problem. :+1:
