### ISSUE TITLE
FEE Not Creating Correct Permalinks

### ISSUE THREAD

**Issue by ksmales23** [iseulde/wp-front-end-editor#206]
Hi 

I love the plugin and using it on a Genesis child theme with Wordpress 4.0.1 all functionality seems to work fine apart from the permalinks.

When I create a new post from the frontend it does not give the post the proper URL..  I have set my permalinks to be /%category%/%postname%/    .... instead it sets it to something like p=3294  

Also I have found that if I leave it as the permalink p=3294 then that post becomes inaccessible after publishing.

This only appears to be resolvable when I manually enter a custom url on every new post and then the posts are fine and accessible again.

Hope you can shed some light on this.

Thanks
Karl

**Comment by iseulde** [comment]
This should be resolved as the UI for a permalink is gone and the post is now saved through the REST API.
