### ISSUE TITLE
The pink "TAKE OVER" button links to redirect loop

### ISSUE THREAD

**Issue by dcastillo3** [iseulde/wp-front-end-editor#210]
Hey, I'm just writing to inform you that the pink takeover button links to a redirect error.

After the redirect loop, I have to manually re-enter my web page URL in the address bar of Chrome, and then I will assume the status of haven "taken over" the article.

This occurs when an administrator is currently editing an article and a different administrator attempts to edit the same article via the "TAKE OVER" button.

![takeover](https://cloud.githubusercontent.com/assets/10469758/5688347/08624e04-9824-11e4-9b5a-41f9e0187435.jpg)

**Comment by iseulde** [comment]
Post locking is gone for now. Might be added back inline later.
