### ISSUE TITLE
Top editing (options) bar is missing

### ISSUE THREAD

**Issue by DigitalApex** [iseulde/wp-front-end-editor#211]
I have been trying to make this plugin work but no matter what I do, I never get the top options bar. I see the admin bar but that's it. 

This is what I did: 

I have a test WordPress website running 3.8....

I performed an update to 4.01. Installed the plugin, the inline editing works fine but no options bar at the top. The same when I started again and updated to 4.1. Editing works but no options bar. 

I have tested this on my theme but also on 2013 or 2014 themes and still no joy. 

I logged in on Firefox and Chrome but again no options bar. Inline edit works fine. 

Not sure what to do next...

**Comment by iseulde** [comment]
That's gone. Everything will be inline now.
