### ISSUE TITLE
Unable to Insert Images After Upload

### ISSUE THREAD

**Issue by jasonwhat** [iseulde/wp-front-end-editor#215]
This may have to do with WP updates, but when I'm writing a post and I click the icon to add an image, I'm able to insert and image already in the Media gallery. However, if I use "Upload" to add a new image the image uploads without an issue, but I'm not able to insert the image. The "Insert" button is grayed out and not clickable.

If I leave the Media library and come back, the image will be in the library and I can now add it. Not ideal.

**Comment by NJoelk** [comment]
I get the same thing

**Comment by jasonwhat** [comment]
Is anybody else seeing this bug? Is it a known issue or a problem with some plugins or hosts? I've tested with 2014 and 2015 themes to check it's not a theme issue and still see the bug.

**Comment by christianwach** [comment]
Yes, same here.
