### ISSUE TITLE
How to disable editor on certain pages

### ISSUE THREAD

**Issue by helms** [iseulde/wp-front-end-editor#216]
Hi,

I'm using wpBeaverBuilder and this plugin conflicts with it.  When activated it hides the default WordPress text-editor on the front-end editing of wpBeaverBuilder.

I would like to disable wpFrond-End-Editor on all pages, since I use wpBeaverBuilder for that, and just have it enabled for posts only (wpBeaverBuilder doesn't edit post in the front-end).  How can I do this?

Thanks in advanced,
Helms

**Comment by iseulde** [comment]
For now you can use the `supports_fee` filter.
