### ISSUE TITLE
Print problems

### ISSUE THREAD

**Issue by Gazzamit** [iseulde/wp-front-end-editor#217]
Hello,

This happens when logged in as admin. When logged in as a subscriber all is OK.

The normally hidden fee content shows up in print preview in chrome or printed pdf's. Also at the bottom of the page there are several lines of warnings as below:

Connection lost. Saving has been disabled until you’re reconnected. We’re backing up this post in your browser, just in case.
The backup of this post in your browser is different from the version below. Restore the backup.
Post restored successfully.

Not sure what the issue is - css emulate print preview looks OK in firefox and chrome.

Regards,

Gary.

**Comment by iseulde** [comment]
This should be gone after 9a10b82.

**Comment by iseulde** [comment]
Actually there are several other print issues...
