### ISSUE TITLE
Feedback about what's editable and what's not

### ISSUE THREAD

**Issue by marcelomazza** [iseulde/wp-front-end-editor#221]
When I click "Edit Post", I get confused about which stuff is editable and which is not. Maybe we can differentiate the editable content somehow. Possible idea, decreasing opacity to everything but the editable content:

![wp-front-end-editor_overlay](https://cloud.githubusercontent.com/assets/384622/6424066/235004ba-bef1-11e4-94d9-35c32ae8a50e.jpg)

**Comment by iseulde** [comment]
We talked about this a lot before, but we could never make it the way we wanted it to work. Keep in mind different colour schemes, drop downs...

**Comment by marcelomazza** [comment]
What if, when you enter Edit mode:

 - We set less opacity for all the elements
 - We set opacity 1 for `.fee-post`, its contents and all its parents

I put together a small test here: http://codepen.io/marcelomazza/pen/KwexqK

@iseulde what do you think?

**Comment by iseulde** [comment]
Now try this with twenty fourteen. :)

**Comment by marcelomazza** [comment]
![front-end-editor-opacity](https://cloud.githubusercontent.com/assets/384622/6428726/01bf660e-bfac-11e4-8803-396badd316f5.gif)

@iseulde ^

**Comment by marcelomazza** [comment]
The effect is even better in crowded templates:

![front-end-editor-opacity1](https://cloud.githubusercontent.com/assets/384622/6428773/bf170260-bfad-11e4-961d-1fd5bb024ac0.gif)

**Comment by iseulde** [comment]
Can you make a patch? I'd have to see this. If you're targeting specific areas based on the theme, that wouldn't work. If you're using the same logic for every theme, and doesn't look weird in any, okay. :) I just don't like the opacity to be 0. You don't have to add my username btw, I get notifications for everything.

**Comment by marcelomazza** [comment]
Done! #223.

The thing with the opacity is that, because we are applying it to nested elements, is not easy to set the correct level. In certain themes it looks great but in other not so... feel free to tweak it and play with it a bit.

**Comment by jasonwhat** [comment]
This seems like an important feature. I'd say one downside of the plugin so far is lack of feedback in the UX, there is very little to tell me I'm in edit mode, or that a post has been saved or published. In fact, I usually open a new tab to check it has been published for fear of losing work. 

+1 for this feature and for some progress bar type mechanism to tell a user when a post has been saved or published.

**Comment by iseulde** [comment]
I've added a dotted outline around editable areas. This is more like a distraction free mode. If your theme is already clean and a good reading experience, then it should be a good writing experience  too. If you don't like writing in your own theme... then maybe it's not such a good reading experience for your readers! :) I'd prefer to keep it like this, but I'll leave it open for consideration. Maybe fading things out isn't that bad, but then again it's not easy to do. The theme could also use the classes and fade things out appropriately if it wanted too.

**Comment by marcelomazza** [comment]
That's great! **A** feedback is better than no feedback at all ;)

I'm glad you are still working on this 👍
