### ISSUE TITLE
W3 Total Cache's HTML minification breaks the media lightbox.

### ISSUE THREAD

**Issue by fastlinemedia** [iseulde/wp-front-end-editor#222]
When W3 Total Cache's HTML minification is on, the media lightbox doesn't appear when trying to add a photo. There aren't any JavaScript errors so I'm suspecting that this has something to do with the Underscores templates being minified.

**Comment by fastlinemedia** [comment]
It looks like a temporary bandaid could be to tell W3 not to minify like so...

define( 'DONOTMINIFY', true );

**Comment by iseulde** [comment]
Sounds like a problem with the plugin or configuration then.

**Comment by fastlinemedia** [comment]
I did some testing with other plugins that minify the HTML and it appears that this issue is only happening with W3. I'll file a ticket with them. Thanks!
