### ISSUE TITLE
Add New Post and Draft Buttons or Widget?

### ISSUE THREAD

**Issue by jasonwhat** [iseulde/wp-front-end-editor#224]
One of the huge values of FEE is that it can help keep users out of the WP backend. This is ideal if you want most users to simply focus on writing. However, there is no way for them to see drafts, and I can't find a way to create a "New Post" button that mimics the one in the admin bar.

What code does one need to create a "New Post" link that launches a new post in FEE instead of going to the backend and basically mimics the "New" link in the admin bar?

I've seen some PHP samples for drafts, but I think a widget could be a good way to solve this and make sure users have access to their draft links on the front end.

**Comment by stkjj** [comment]
+1

**Comment by jasonwhat** [comment]
Any advice on code I could put in a sidebar to replicate the "New Post" functionality. I tried to look at the code, but not sure exactly what I need.

**Comment by dennisjover** [comment]
+1 on this

**Comment by jackjamil** [comment]
+1 . It would be so much easy ...

**Comment by gingebean** [comment]
+1

**Comment by iseulde** [comment]
See #58.
