### ISSUE TITLE
Where is its functionality???

### ISSUE THREAD

**Issue by testerboy65** [iseulde/wp-front-end-editor#225]
It does nothing except to make page as draft/published
Where is its real functionality???
Its name refers that we can easily edit posts on front side 
Please see the screenshot below
http://content.screencast.com/users/QATeamOfficial/folders/Default/media/fdca3358-a21b-4546-9a85-4d59587ba580/plug.png

Thanks

**Comment by dnaber-de** [comment]
Using the plugin with a default theme allows you to write direct inside the text of the content by pacing the cursor inside the content and then just typing…

If it does not work with the theme you use, I suggest to provide more information about the setup you use.
