### ISSUE TITLE
Not working with Drone Genesis Child Theme

### ISSUE THREAD

**Issue by lisaleague** [iseulde/wp-front-end-editor#226]
Thanks for this plugin. I'd like to be able to use it with this theme - http://zigzagpress.com/portfolio/drone-theme/ but it's not working. Hope this info helps.

**Comment by iseulde** [comment]
It's a premium theme so I can not test. It looks like it's a JavaScript theme which is not supported at the moment. Please contact the theme author about this problem. Feel free to reopen, but I would need to be able to test it myself.
