### ISSUE TITLE
Theme requirements for this plugin to work?

### ISSUE THREAD

**Issue by lmartins** [iseulde/wp-front-end-editor#231]
Hi,

Um building my WordPress websites using Timber and since i've started with that workflow Front-end Editor stopped working on my projects. I wonder what are the requirements to be able to use it.

Thanks.

**Comment by bryanwillis** [comment]
I'm guessing it could have to do with when each one of these plugins hook into the wordpress functions that display the content. Depending on when timber compiles everything and outputs it as php, Front-End-Editor may have already tried hooking into the template at an earlier priority, which doesn't contain any functions like the_content(), the_title(), etc...

What exactly are your results when trying to use the plugins together? Does anything happen at all?

I've used twig in the past, but haven't messed with timber before. If you just want a quicker way to write templates another option to try is https://wordpress.org/plugins/custom-content-shortcode/screenshots/.

It's practically the same idea, but just uses shortcodes. instead. You can even put the shortcodes in actual files inside your theme. While it also doesn't have support for front end editor you can use https://wordpress.org/plugins/live-edit/ as an alternative for it. Personally, I use front end editor for simpler blogs that don't need that advanced of templates.

**Comment by iseulde** [comment]
The new update should work. If you're still having problem please reopen this issue. There are no theme requirement, but some themes can give problems. JavaScript themes are also not supported atm.
