### ISSUE TITLE
Smileys not working

### ISSUE THREAD

**Issue by hooge229** [iseulde/wp-front-end-editor#232]
Hi,

I noticed the smileys do not work. For example:

Backend editor: type ':)' and it resolved to an smiley at the front-end:
img src="http://www.website.com/wp-includes/images/smilies/icon_smile.gif" alt=":)" class="wp-smiley"

If I use the front-end editor, the following is created:
img src="http://wp/http://wp/src/wp-includes/images/smilies/icon_smile.gif" alt=":-)"

So, it could not been resolved. I found the URL in /plugins/wp-front-end-editor/js/tinymce.markdown.js. I hope the issue could be resolved.

Thank you.

**Comment by iseulde** [comment]
Yeah. I actually forgot to take that out when I added that file months ago...

**Comment by hooge229** [comment]
Ah okay :) So I guess that feature is not avaiable? And will this issue be solved in the next update?

**Comment by iseulde** [comment]
It is available. The smiley will just not pop up as you type. Just when you leave the editor.
Yeah, I'll remove it.

**Comment by hooge229** [comment]
Great, thank you :)

**Comment by iseulde** [comment]
I'll close this when it's actually done. :)

**Comment by iseulde** [comment]
f06efa03ccdcf28d42edcdc4de1a6147fc88812b
