### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by drakemoore** [iseulde/wp-front-end-editor#234]
I have created a custom post type for my project and the front end editor does not recognize it.  This probably isn't a bug and I apologize if this isn't the proper forum for my question.  Is there a way to make it recognize my post type?

Thanks and amazing work!

Cheers,
Drake

**Comment by drakemoore** [comment]
I found the __construct() method in class_fee.php and added my custom post type with an add_post_type_support call and it appears to be working.  Is there a way I can hook into this without hacking at your plugin code?

Thanks!

**Comment by the2003s** [comment]
I'm having the same issue, Custom post type support would be amazing!

**Comment by axelson** [comment]
+1

**Comment by redblueconcepts** [comment]
Ideally, it would be awesome if plugin and theme authors could add front-end editability as a support for their CPT when they register it. Would this be a possible way to implement? This is the single reason I don't use this on every site – it's too difficult to train clients if there are two different paths to editing for them to learn based on the CPT they're using. (Well, this and custom field support.)

**Comment by hooge229** [comment]
This would be a great feature. I was just looking for it. I hope this could be implemented. Maybe with get_post_types() and add the result to the add_post_type_support?

**Comment by AppSynergy** [comment]
+1

**Comment by holisticnetworking** [comment]
The down side of a CPT editor is the need for custom fields. But if there was a way to make front end editing work for CPTs (still an under-appreciated concept, even to devs, it seems), that would be great.

**Comment by redblueconcepts** [comment]
The last comment is 100% on point. Custom fields are almost a necessity when you're supporting CPTs.

**Comment by iseulde** [comment]
See #20 and #49.

**Comment by drakemoore** [comment]
Thank you Ella!

Cheers,

Drake Moore
MagickMedia.com
604.700.4232
