### ISSUE TITLE
What tables in database?

### ISSUE THREAD

**Issue by arniarni** [iseulde/wp-front-end-editor#237]
Hi,
Tell me please these tables from this plugin?
wp_wpfront_ure_options
wp_wpstorecart_meta

**Comment by zanematthew** [comment]
Never seen those, I've been using this plugin since the early days (0.x) releases and haven't seen those tables show.

**Comment by Kuzmanov** [comment]
Those tables are used in some older versions of two other plugins, they're not from WP Front-end Editor.
