### ISSUE TITLE
Hitting the ESC key while editing throws fatal JS error

### ISSUE THREAD

**Issue by jambox** [iseulde/wp-front-end-editor#238]
Hey great work on the plugin so far.

I'm getting the following error in the console when I hit the ESC key:

`Uncaught TypeError: A.html is not a function`

It seems to be a fatal error as I can't reinitialize the editing session by re-clicking "Edit Page". I'm using a custom theme I built so it could totally be an issue related to my theme being incompatible, but I just wanted to report it in case it's not. Is there a debug mode I can trigger from the plugin to see where the error is coming from in the unminified JS?

Thanks again for building this thing! Really ambitious step in the right direction for WP...

**Comment by iseulde** [comment]
I removed escape now.
