### ISSUE TITLE
Project future ?

### ISSUE THREAD

**Issue by kosir** [iseulde/wp-front-end-editor#240]
Hi sorry for posting my question here, but it's kinda issue for me.
I'm looking for opensource front-end editor for wordpress and found your project, which looks really fast and clean, congrats!
But just after that I found that your project is under Inactive Feature Plugins
(These feature plugins are no longer being worked on) on wordpress.org (https://make.wordpress.org/core/features-as-plugins/).
What does that mean? Is this project abandoned (in favor of some other more advanced front-end editor) or project is maybe finished and there will be no more development...? Will there be support for developers in the future? Just want to know this before I start to use it...
Since it is open source I know that this is kinda stupid question, but please let me know, so I can understand what can I expect.
Thanks in advance for any reply!

**Comment by solhuebner** [comment]
This is from WordPress 4.3 Kickoff ( https://make.wordpress.org/core/2015/04/28/wordpress-4-3-kickoff/ ):

WordPress 4.3 will be all about enabling users of touch and small-screen devices. @ryan has been testing flows on a myriad of different devices the past few releases and uncovered many things that desperately need attention.

    **Editor led by @azaozz and @iseulde**
    Admin UI led by @helen
    Network admin UI led by @jeremyfelt
    Partial Refresh led by @westonruter
    Customizer Transactions led by @westonruter
    Install process and passwords led by @markjaquith

So it looks like it will get a push for WordPress 4.3 :)

**Comment by christianwach** [comment]
I'd be interested to know if this means there will be some TLC given to this plugin or simply to TinyMCE.

**Comment by kosir** [comment]
@solhuebner thanks, that's really good news. I really didn't understand, why such a good project would be deprecated... Good luck.

**Comment by christianwach** [comment]
Sadly, it seems like the focus is on TinyMCE, not this plugin: https://make.wordpress.org/core/2015/05/01/editor-wish-list-for-4-3/

**Comment by Mte90** [comment]
any news?

**Comment by refactorsaurusrex** [comment]
> any news?

Yeah, I too would like to hear if there's any status update on this project.

**Comment by iseulde** [comment]
Patience. :)

**Comment by refactorsaurusrex** [comment]
> Patience. :)

If I must. :)

**Comment by iseulde** [comment]
Working on it.
