### ISSUE TITLE
Add featured Image to Post

### ISSUE THREAD

**Issue by derweili** [iseulde/wp-front-end-editor#242]
My theme displays the featured image only on archive page but not on single page, so can not find a way to add it with the frontend editor.
Is there a way to add the featured image via front end editor for themes which do not display the featured image on single page?

Thanks for your help.

**Comment by eliorivero** [comment]
Hi Julian, unfortunately if the theme doesn't support the featured image in pages, you won't be able to add it with the FEE, since FEE can only produce content for the features supported by the theme and it's the theme the one that should support & display them.
