### ISSUE TITLE
Posting from frontend makes "?p=123" instead of defined numeric permalink

### ISSUE THREAD

**Issue by ezkay** [iseulde/wp-front-end-editor#243]
Hi! Great Plugin!

But something konfuses me.. When i create a post via a link on the frontend, it makes a standard permalink (http://example.com/?p=123) instead of numeric permalink (http://example.com/blog/Archive/123). When i post from backend the permalink is set right.

**Comment by iseulde** [comment]
When creating a post? That's normal is it's an auto-draft. As soon as you publish it will be pretty.
