### ISSUE TITLE
Warning line 279 on BuddyPress sites

### ISSUE THREAD

**Issue by ezkay** [iseulde/wp-front-end-editor#247]
Hi! I have an error on all BuddyPress sites on my website. Everything works fine, but at the top of the page i get:
"Warning: implode(): Invalid arguments passed in /xyz/wordpress/wp-content/plugins/wp-front-end-editor/class-fee.php on line 279"

**Comment by Mat2012** [comment]
Same problem here. Seems that this - wonderful - plugin is not completely compatible with BP. Nice work, though.

**Comment by iseulde** [comment]
How are you using this plugin in BuddyPress? I'm not very familiar with BuddyPress. I'll look into the issue. Patch welcome. :)

**Comment by christianwach** [comment]
Isn't this solved by #227?
