### ISSUE TITLE
Can't play videos?

### ISSUE THREAD

**Issue by ezkay** [iseulde/wp-front-end-editor#249]
When i inserted a video gallery, the video gets overlayed by a black layer. just showing "download file" in the upper left corner. When refreshing the site, i see the "play" button but also nothing happens. not even the timline-pin is moving nor time is running.
Same thing in any tested standard theme..

**Comment by iseulde** [comment]
I updated core scripts and tinymce so this should be gone. Please reopen this issue if there are still problems.
