### ISSUE TITLE
Issues with multi user blog

### ISSUE THREAD

**Issue by nicoleRLMG** [iseulde/wp-front-end-editor#251]
Hi there, 

We really love your plugin and are using it quite frequently on a colaberative blog for creative ideas.  Unfortunately, two (or more) users cannot view the same page or post without one of them being frozen out (as though someone was editing the page or post).  This error occurs when neither user is editing the page or post.  It seems editing is the plugin default mode?  When, deactivated the issue is gone, allowing multiple users to simultaneously view the same post or page. 

We would really love to continue to use your plugin. Is there any chance this will be resolved? 

Thanks!

**Comment by kuroblack** [comment]
Idem. Page/post is already being locked even when another user was just viewing it. Preview didn't work, and taking over access caused "ERR_TOO_MANY_REDIRECTS" on my web page.

I hope this issue will be fixed soon. Thanks!

**Comment by rraub** [comment]
We fixed this issue in our fork of this repo (as well as a number of other things) if you want to give it a try: https://github.com/gios-asu/wp-front-end-editor

With all the stale pull requests for this repo we haven't bothered to try and isolate out individual fixes and make pull requests for them.

**Comment by iseulde** [comment]
Pull requests welcome. :)

**Comment by rraub** [comment]
@iseulde I fully intend to get our act together and start issuing some, I just got to isolate our changes into features so that way its not too huge of a PR to review.

**Comment by iseulde** [comment]
@rraub Thanks! Yeah, the smaller the better. I'll take a look at your fork.

**Comment by iseulde** [comment]
Which commit fixes this? I'll take a look and fix this for the next release.

**Comment by rraub** [comment]
It was a bit of work if I recall correctly, we had to change when the locking was being made. It should be in this old PR https://github.com/gios-asu/wp-front-end-editor/pull/12 but unfortunately with the changes in whitespace the diff isn't really useful on github.

**Comment by iseulde** [comment]
Atm post locking is removed from this repo (so it makes it easier for me to move things around), but I'll add it back. While looking at the old code I saw some mistakes, so maybe solving these will fix it. I'll also have a look at those commits, thanks!

**Comment by iseulde** [comment]
Okay post locking is gone for now. Curious to see how applications using the REST API would handle this. Not that it needs to go through that though. I'll look at post locking again once the "main" feature is done.
