### ISSUE TITLE
WordPress 4.3 issues

### ISSUE THREAD

**Issue by r-a-y** [iseulde/wp-front-end-editor#257]
**Issues:**
- Console errors when clicking on the "Edit Page" button to turn FEE on - commit 0569644
- Floating toolbar doesn't show up - commit cc94a5c (hack fix; this should be fixed properly!)
- Clicking on the 'remove' button multiple times in the image floating toolbar removes parent elements - see issue no.266

My compiled fixes for current release version:
https://github.com/iseulde/wp-front-end-editor/pull/261/files

My compiled fixes for development version on GitHub:
https://github.com/iseulde/wp-front-end-editor/pull/268/files

**Comment by phpbits** [comment]
Hi,

I did some testing too and I'm encountering this issue. Tried to contact the author via slack but I'm not getting any response yet. Thanks!

<img width="1273" alt="screen shot 2015-08-20 at 3 14 42 pm" src="https://cloud.githubusercontent.com/assets/3365507/9377635/8867e4aa-474d-11e5-9ed8-a58c37d3ce73.png">

**Comment by phpbits** [comment]
Hi,

Did you find any solution? Thanks!

Cheers,
phpbits

**Comment by r-a-y** [comment]
I cannot verify the error messages that @phpbits posted above, but on my install, I was able to get FEE working again by disabling the `'wplink'` TinyMCE plugin.

The `'wplink'` plugin received updates in WordPress 4.3, which is not compatible with FEE's JS.

The following snippet removes `'wplink'` from FEE's TinyMCE plugins and fixed things for me:

```php
/**
 * Removes the 'wplink' TinyMCE plugin from FEE.
 */
function my_fee_tinymce_remove_wplink( $retval ) {
	$key = array_search( 'wplink', $retval );
	if ( false !== $key ) {
		unset( $retval[$key] );
	}

	return $retval;
}
add_filter( 'fee_tinymce_plugins', 'my_wp_fee_tinymce_remove_wplink' );
```

This should be considered a temporary workaround as I'm not sure what iseulde plans on doing with `'wplink'` with FEE.

If you're using the code snippet above, you still need to apply my PR in #261.

**Comment by NicktheGeek** [comment]
Note for anyone attempting this work around. The callback and function in the example do not match. The code should be updated to 
~~~php
/**
 * Removes the 'wplink' TinyMCE plugin from FEE.
 */
function my_fee_tinymce_remove_wplink( $retval ) {
    $key = array_search( 'wplink', $retval );
    if ( false !== $key ) {
        unset( $retval[$key] );
    }

    return $retval;
}
add_filter( 'fee_tinymce_plugins', 'my_fee_tinymce_remove_wplink' );
~~~

For sanity's sake you may want to edit the callback and function name to use a prefix other than "my_" just in case a plugin or theme happens to be using that same prefix.

This update caused it to *mostly* work for me. I'm working on identifying some CSS issues. May be due to the custom setup I have.

**Comment by r-a-y** [comment]
Thanks for the catch about the filter callback.  Updated.

**Comment by laurgaut** [comment]
Hello,
wa can see that 4.3.1 version of wordpress corrects the wplink tinymce plugin

https://codex.wordpress.org/Version_4.3.1
TinyMCE: Plugin wplink throw js TypeError: editor.wp undefined #33393

I think, after this update installation, FEE will work

**Comment by NicktheGeek** [comment]
I can confirm that after 4.3.1 was updated and the max version was increased in package.json I was able to remove the code that stopped the wplink from loading and everything worked.

**Comment by r-a-y** [comment]
I can also confirm that WP 4.3.1 fixes the issue with the 'wplink' TInyMCE plugin.

I've updated the package.json as well in my pull request.

**Comment by r-a-y** [comment]
I've encountered one issue in WP 4.3.x.

After adding a media item with FEE, the toolbar does not show up when you mouseover the item.  In WP 4.2, this toolbar showed up:

![Screenshot of toolbar](https://cloud.githubusercontent.com/assets/505921/10260293/bd8687c0-6928-11e5-95d0-4117b5bcdb0e.png)

Will report back if I find a fix.

**Comment by picajoso** [comment]
Hi, I've just tried updating to WP-4.3.1 but the plugin is still not working there. I'm conflicted because I'd like to continue using this fantastic plugin, but my blog security is at risk if I don't update to the latest WP... 

I wonder if there's a public update to the plugin that normal users like me (I'm a bit lost when you talk about those kind of patches) can use in the near future. Is there an easy way to make this work with WP 4.3.1?

Regards!

**Comment by picajoso** [comment]
I've updated my blog to WP-4.3.1 and as r-a-y says, the toolbar isn't present anymore, you've got to hover just over the selection to see the little indication that allows you to insert a link, put in bold or italics, etc. I've edited the two files r-a-y mentions on the plugin's code, but no luck whatsoever. 

![image](https://cloud.githubusercontent.com/assets/853760/10304749/58d6b84e-6c1c-11e5-9f8e-574bb68c2af1.png)

Is there a new version fixing this coming soon?

**Comment by r-a-y** [comment]
>  I've edited the two files r-a-y mentions on the plugin's code, but no luck whatsoever.

You have to clear your browser cache to see the changes.

**Comment by picajoso** [comment]
I'm affraid that doesn't make any difference. I've tried to use different browsers and even a incognito session on them, and it still doesn't show the toolbar :(

**Comment by r-a-y** [comment]
I think I see the problem.  I have `SCRIPT_DEBUG` set to true:
https://codex.wordpress.org/Debugging_in_WordPress#SCRIPT_DEBUG

So I'm loading the unminified JS files during testing.  I need to patch the minified JS file as well for production use.  I'll try to get to this soon, but in the meantime, you could set `SCRIPT_DEBUG` to true and it should work.

**Comment by picajoso** [comment]
Thanks for the tip, but it isn't working :( As far as I know setting that to true is the only thing I have to do. I don't need to restart my webserver, for example. So I've made the change, but nothing happens. Still no toolbar.

**Comment by r-a-y** [comment]
Check your JS and see if the changes you made are actually implemented.

Try purging your cache in both the browser and WP cache (if you're using 
a caching plugin).

**Comment by r-a-y** [comment]
Since iseulde's latest commits to bump compatibility for WP 4.3, I'm still encountering issues.

Here are my latest fixes:
https://github.com/iseulde/wp-front-end-editor/pull/268/files

**Comment by iseulde** [comment]
I know not everything is fixed. There are quite a lot of remaining issues. Sorry for the inconvenience!

**Comment by picajoso** [comment]
WordPress 4.4 has come and there are new problems. I wonder if you can take a look iseulde. r-a-y, maybe you can see if you can do something too?

**Comment by iseulde** [comment]
Anything left here, please make a list. :) Thanks!

**Comment by picajoso** [comment]
It's working really great, thank you @iseulde !

**Comment by iseulde** [comment]
Thanks! New issues for new problems please.
