### ISSUE TITLE
WordPress 4.3 support

### ISSUE THREAD

**Issue by picajoso** [iseulde/wp-front-end-editor#259]
I've updated my blog to WP 4.3 and I've seen that the plugin supports 4.3-alpha but not the final one. I wonder how much time will it take to support it, I'm considering going back to my previous version of WordPress -I've made a backup- just to be able to work with WP FrontEnd Editor (I love it!)

Thanks!

**Comment by phpbits** [comment]
Please check : https://github.com/iseulde/wp-front-end-editor/issues/258 . I'm also waiting for the plugin update. Thanks!

**Comment by picajoso** [comment]
Ups, you're right. I¡ll delete this and check that thread and #257, thanks
