### ISSUE TITLE
Editing pages and custom posts

### ISSUE THREAD

**Issue by paulbarris** [iseulde/wp-front-end-editor#260]
Hi!
Thanks for this great plugin :)
I was wondering,  might it also work on pages and custom posts? 
Thanks!
Betsy

**Comment by phpbits** [comment]
Hi,

You just have to add :

add_post_type_support( 'page', 'front-end-editor' );

change 'page' to custom post type. It's not working on the latest wordpress version though. I'm waiting for this plugin to be updated. Thanks!

Cheers,
phpbits

**Comment by iseulde** [comment]
See #234.
