### ISSUE TITLE
Remove button in floating image toolbar removes more than the image on subsequent clicks

### ISSUE THREAD

**Issue by r-a-y** [iseulde/wp-front-end-editor#266]
When the "X" button is clicked multiple times in the floating image toolbar, it removes parent elements as well.

Here's a GIF detailing what happens:

![GIF](https://cloud.githubusercontent.com/assets/505921/10291760/5db5b3f4-6b60-11e5-8d33-49db051dedec.gif)

No JS errors in the console.  Tested in WordPress 4.2.5 with twentytwelve (also occurs in other themes).

Looks like there is an issue with the `removeImage()` function in `tinymce.image.js`.

**Update:** I've added a PR for this - https://github.com/iseulde/wp-front-end-editor/pull/267/files.

**Comment by iseulde** [comment]
Fixed in 51539d8.
