### ISSUE TITLE
Collaboration with WA Fronted?

### ISSUE THREAD

**Issue by jesperbjerke** [iseulde/wp-front-end-editor#269]
Would a collaboration or merger between FEE and [WA Fronted](https://github.com/jesperbjerke/wa-fronted) be of interest?

**Comment by iseulde** [comment]
What kind of collaboration?

**Comment by jesperbjerke** [comment]
Well, my thought was that it might be a good idea if the two project could merge together, getting one strong contender instead of having two separate projects working at the same goal. Fronted has a focus of being extendable and developer friendly. A merger might complement the two projects into a better end product.

**Comment by jesperbjerke** [comment]
I have forked your tinymce theme (not yet commited though). I hope thats OK.
