### ISSUE TITLE
Plugin does not work with 4.3.1  non alpha version

### ISSUE THREAD

**Issue by BeckyBruso** [iseulde/wp-front-end-editor#270]
Hi-

I wanted to note that this plug in gives the following message with non beta installation of 4.3.1 WordPress:  "WordPress Front-end Editor currently only works between versions 4.1 and 4.3-alpha."
This is above the post editor when you go into edit a post.  A screen shot of this message has been  included for your reference.  
![front-end editor github](https://cloud.githubusercontent.com/assets/15196417/10579035/ce04d9d0-7643-11e5-9129-124c6fa06c00.JPG)
Hope to see this feature enabled for compatibility with the newest WordPress version as it will save me ( and many others!!)   countless hours going back and forth between the front-end and back end to do minor editing tasks.  

Thanks.
Becky

**Comment by iseulde** [comment]
It should now! Sorry!
