### ISSUE TITLE
Auth script error

### ISSUE THREAD

**Issue by koniklos** [iseulde/wp-front-end-editor#272]
Hello,
Thank you very much for this wonderful plugin!

I've installed version 1.1.0 and there's a couple of issues I've run into.

Trying it out on WP 4.4.1 with Twenty Fifteen 1.4, the plugin works fine. 

The issues there, is that I'm getting an error in console 
**"Uncaught TypeError: Cannot read property 'hasClass' of undefined"** 
from **wp-auth-check.min.js** 
and the message **"The content on the server and the content in the editor is different. This may be due to errors."** from **fee.min.js**.

If the plugin is disabled there's no error.

When I've changed themes, in particular I've tried it with Twenty Sixteen 1.1 and a fresh copy of underscores starter theme, I couldn't update nor cancel the changes. The error in the console was **"Uncaught TypeError: Cannot read property 'body' of undefined"** from **tinymce.min.js.**

All these on localhost, with fresh WP installation and only wp-front-end-editor running.

I'm attaching two (2) gif files, demonstrating the issues mentioned above.

![anim-01](https://cloud.githubusercontent.com/assets/16817817/12487826/902e6964-c071-11e5-9cc6-849725ede888.gif)

![anim-02](https://cloud.githubusercontent.com/assets/16817817/12487827/9030006c-c071-11e5-8ad7-b681308bf877.gif)

**Comment by iseulde** [comment]
Thanks for your feedback. You can safely ignore the message "The content on the server and the content in the editor is different. This may be due to errors." I will investigate the others. It looks like the body error only happens with the latest theme.

**Comment by mariusveltan** [comment]
Hi, all!

"body" error indeed gets triggered on theme Twentysixteen, when initializing the editor on the "screen-reader-text" element of the post Edit Post link, to the side of the post content (screenshots below).

<img width="480" alt="screen shot 2016-05-25 at 23 19 31" src="https://cloud.githubusercontent.com/assets/6448452/15555053/9db71c0a-22cf-11e6-9ab0-a6d997b802ed.png">
--------------------------------
<img width="508" alt="screen shot 2016-05-25 at 23 19 59" src="https://cloud.githubusercontent.com/assets/6448452/15555052/9db628ea-22cf-11e6-9d2d-d75d400f5bc4.png">

**Comment by iseulde** [comment]
Removed in cbccd5c.
