### ISSUE TITLE
Visible space for featured image

### ISSUE THREAD

**Issue by derElch** [iseulde/wp-front-end-editor#273]
its possible to edit the title of the post without having clicked to edit the post. its only work for the title, not for the content. its not possible to save the new title, after reloading page it's still the original title.

in connection to this bug, if an post have NO post thumbnail, there is a visible space for it. it's only visible as logged in admin/editor/writer, not as visitor.

Wordpress 4.4.2, front-end-editor 1.1.0. current theme is a modification of Twenty-Fifteen 1.4

**Comment by AlexandruDoda** [comment]
+1

**Comment by kuroblack** [comment]
+1
happens even with all other plugins disabled.

**Comment by mykthex** [comment]
+1 happens to me too.

**Comment by iseulde** [comment]
Fixed in 32e4caf. I'll look into the other issue, but maybe create a separate ticket?
