### ISSUE TITLE
Suggestion/Requests

### ISSUE THREAD

**Issue by ChristoferL** [iseulde/wp-front-end-editor#275]
It would be good to allow 'add a block' to always be present below the 'invisible text box'. There are occasions I have seen add a block refuse to pop up. This would solve that and provide a navigational target for those fishing for the text area.

Also, adding a 'select category' feature would make the entire process complete, IMHO.

**Comment by iseulde** [comment]
Do you mean when there is no content? Could you explain the 'select category' feature?

**Comment by iseulde** [comment]
I've removed the "add a block" thing. It is now permanently visible in a toolbar. Feel free to create a new issue for the feature.
