### ISSUE TITLE
word press fronted  adverse editor 

### ISSUE THREAD

**Issue by johiruddin** [iseulde/wp-front-end-editor#277]
dear honey able sir 
In WordPress where we add page or post It is solid color but 
we want to edit as like as theme editor

**Comment by johiruddin** [comment]
![screenshot 18](https://cloud.githubusercontent.com/assets/17114882/14216762/55cbcb80-f86c-11e5-91dc-f881f1c29699.png)

**Comment by johiruddin** [comment]
this type of system we edit in wp-admin 
![screenshot 19](https://cloud.githubusercontent.com/assets/17114882/14216823/a6d0b68a-f86c-11e5-87f2-7d71b4beee59.png)

**Comment by johiruddin** [comment]
please advise if have any plugin

**Comment by kashmirix** [comment]
Are you reporting any bug related to this plugin? This is a bug tracker, not an advice board.

Also, plugin author is not "sir".

**Comment by iseulde** [comment]
I'm not sure what this is about, please clarify and reopen, thanks!
