### ISSUE TITLE
Duplicated content

### ISSUE THREAD

**Issue by thisispad** [iseulde/wp-front-end-editor#278]
Plugin works great

Except post content (minus title) is duplicated on page load. Pressing edit removes it, cancelling edit shows just one correctly. 

Titles are always editable (bug?)

Have disabled all plugins and other js but no improvement.

Would love to fix as the plugin is wonderful.

**Comment by iseulde** [comment]
This should be fixed in 32e4cafba34fb67c1635dc913003b3717ec9efd1.
