### ISSUE TITLE
Conflicts With Bootstrap Modal Window

### ISSUE THREAD

**Issue by 1wdtv** [iseulde/wp-front-end-editor#279]
Seems to conflict with the modal window trigger in Bootstrap 3.0

When one has a modal window, and front-end-editor is active, the modal window will trigger and then 
cycle immediately back to a closed state.

I'm thinking you should possibly have a unique ID and target ID for the editor instead of the default from Bootstrap?

**Comment by iseulde** [comment]
Removed the category editing for now. I'll redo this without Bootstrap.
