### ISSUE TITLE
Compatibility with WordPress 4.5.3

### ISSUE THREAD

**Issue by m-exner** [iseulde/wp-front-end-editor#280]
After activating this plugin after upgrading to WordPress 4.5.3 I receive the following error message on the dashboard and on my website:

Notice: get_currentuserinfo is deprecated since version 4.5! Use wp_get_current_user() instead. in /hermes/walnaweb10a/b1983/moo.(website name)/wp-includes/functions.php on line 3658

I cannot find the code for "get_currentuserinfo" to remove. Can you check to see if this plugin is compatible with WordPress version 4.5.3?

Thanks.

**Comment by iseulde** [comment]
No `get_currentuserinfo` in this plugin, sorry! Maybe it's some other plugin? Please reopen if you found that it's a problem with this plugin.
