### ISSUE TITLE
Update and Abort buttons do not work (WP 4.5.3)

### ISSUE THREAD

**Issue by mpstiller** [iseulde/wp-front-end-editor#281]
After upgrading to WP 4.5.3 both the "Update" and "Abort" buttons are not working anymore. The editing functionality still works fine - I am able to edit pages and articles, but cannot save or discard changes afterwards as clicking on the respective buttons in the toolbar does not lead to any actions.

FEE version: 1.1.0

Thanks

**Comment by iseulde** [comment]
Will look into it.

**Comment by iseulde** [comment]
I have moved these. Please reopen if it's still an issue with this alpha.
