### ISSUE TITLE
Cant install Fatal error: Class 'WP_REST_Controller' not found

### ISSUE THREAD

**Issue by cascompany** [iseulde/wp-front-end-editor#283]
## Expected behaviour and actual behaviour

Tried to install
and got : 
Fatal error: Class 'WP_REST_Controller' not found

## Specifications

* Browser Name and Version:  Chrome Mac
* WordPress Version:  4.5.3
* Plugin Version:  1.0.4  (i think, just downloaded from github)
* Theme name/URL:  Divi

**Comment by iseulde** [comment]
Thanks for the report. I can reproduce.

**Comment by iseulde** [comment]
Fixed in f6dd9a82b0206535f2e0c30a56e6c39f8bd1569a.
