### ISSUE TITLE
Plugin not working...

### ISSUE THREAD

**Issue by jerayan** [iseulde/wp-front-end-editor#285]
## Expected behaviour and actual behaviour

Plugin stops working (button **Update** and **Cancel**) if add gallery. Text toolbar not working at all.

## Steps to fix the problem

Delete this fragment of code in file **mce-view-register.min.js** in plugin folder _wp-front-end-editor\js\_

> e.appendChild(_.isString(a)?c.dom.createFragment(a):a),b&&b.apply(this,arguments)},c)},

## Specifications

* Browser Name and Version: Google Chrome v51
* WordPress Version: 4.6 Beta 3
* Plugin Version: 1.1.0
* Theme name/URL: All themes

## Error messages
**Uncaught TypeError: Cannot set property 'innerHTML' of undefined**
_mce-view-register.min.js?ver=1.1.0:1_

**Comment by iseulde** [comment]
Hi, thanks for the report! This is resolved here on GitHub but I have yet to release a new version with the WordPress plugin directory, which should not take too long now. Look out for version 2. :)
