### ISSUE TITLE
A practical review of Front-end Editor 2.0.1

### ISSUE THREAD

**Issue by picajoso** [iseulde/wp-front-end-editor#292]
First of all, thanks to you, Iseulde, for this great plugin that has allowed me (and many others, I'm sure) to enjoy writing on their blogs.

I've been a WP Front-end editor user since I discovered it [two years ago](http://www.javipas.com/2014/07/02/wordpress-y-su-editor-frontend-haran-temblar-a-medium/) , and I've seen how it has been updated in that time. I'm affraid the new version has disabled options that were really useful. 

I guess there's going to be changes to bring those features back. I've tried to find information about the new 2.x series and its dependence on the WP REST API but I haven't found none, maybe you could explain what has happened and clarify the reasons, Iseulde

On the last 1.x version we had options to save a draft and go back to the WP admin native editor on its backend to continue the draft from there. These options are now gone and you can only publish the post. 

The "+" symbol on that bar on the top of the page (covers a little part of my header or header image and it makes the preview look a little bit uglier) also allows only to insert an image or a gallery. The options for the previous versions of the plugin were more interesting and better presented too. The usability was IMHO also better. 

That is also true with the new paragraph style that is available through that "¶" symbol. This was far easy to do on the previous version by selecting the text and aplying the style. 

The boxes that now appear rounding every block of content -featured image, title, actual post- make also the writing experience more ugly and inconvenient, like when you fill out a form. There's no more "Add Block" option when you left a new line empty. 

![boxes](https://cloud.githubusercontent.com/assets/853760/17549602/4865b9d8-5ef1-11e6-9a8c-84e8fe8bbea0.jpg)

There's also some ideas for future versions that could be useful. I'm using the "Press This" [bookmarklet](https://codex.wordpress.org/Press_This) in other blog I've got and the editing options are not so nice as 1.x versions of WP Front-end Editor, but there's something I really like: the ability to add category and tags straight from there:

![pressthis](https://cloud.githubusercontent.com/assets/853760/17550624/2d32a784-5ef6-11e6-8f8d-cecc32c01e02.jpg)

I hope this is taken as constructive, I really love this plugin but this last version has been a littel disappointment :/

Best

Javier Pastor

## Specifications

* Browser Name and Version: Chrome 52.0.2743.82 m / Windows 10 
* WordPress Version: 4.5.3
* Plugin Version: 2.0.1.
* Theme name/URL: Ryu (modified version)

## Error messages

None

**Comment by iseulde** [comment]
Thanks for the feedback!

I know some features have been removed for now to allow me to develop it faster, like tags and categories, but don't worry, most will be added again soon. I recreated the editor almost from a blank slate.

The save button is indeed gone, but you can still create drafts. The post continually saves in the background, and you can leave the page any time and edit the draft in the admin.

The + thing etc. have indeed moved but hopefully we can improve it and present it better. It seems it doesn't work out that well at the top of the page.

The borders have been added after comments that it was hard to know which areas were editable. I've already made them a bit thinner (yet to be released) and maybe they should be hidden once you start writing. Not sure how that should work yet.

**Comment by iseulde** [comment]
Maybe we can go over these points one by one and address/fix them? It would be easier in separate tickets.

**Comment by picajoso** [comment]
Thanks for the quick answer Iseulde!

Great! I've seen drafts are automatically saved so that's nice, but without any hint it could be difficult for new users to know that. 

I'll create separate issues for each one then. Most of them are not "issues" per se, but things I think could be nice to have (or have back). The plugin works really well aside from my personal opinion.

Javi

**Comment by iseulde** [comment]
> Great! I've seen drafts are automatically saved so that's nice, but without any hint it could be difficult for new users to know that.

Yeah you're right, but I'd like users to get used to the idea that they don't have to save posts. In Google Docs for example I think people are comfortable with that. We could add some indicator but I'm not exactly sure where yet. And it shouldn't be annoying.

**Comment by picajoso** [comment]
I've created indvidual issues now, hopefully that will help. Thank you again for that great work!

BTW, could you explain the move to the WP REST API and rewriting this from scratch?

**Comment by iseulde** [comment]
Thanks! Your issues will be addressed soon.

> BTW, could you explain the move to the WP REST API and rewriting this from scratch?

It uses the REST API now so that this plugin doesn't have to deal with all those things. The REST API is meant for things like this. I've rewritten the plugin since there were a lot of bugs with the way the old version worked, like duplicate content. I hope it's now also easier for other people to contribute to the code.

**Comment by picajoso** [comment]
Great, thanks for taking care of all of this :dancer:

**Comment by iseulde** [comment]
I'm going to close this in favour of #293, #295, #296 and #254. Looks like everything is covered there.

**Comment by picajoso** [comment]
Great! I'll add new issues if I see something. Btw, I've notice one more thing: the blockquote option is no longer available when you select text :(

**Comment by iseulde** [comment]
Oh yeah.... Will add it back. For now you can use `> text` and press enter.

**Comment by picajoso** [comment]
I was doing it from the WP editor, but that's good to know!
