### ISSUE TITLE
Bring headings etc. inline

### ISSUE THREAD

**Issue by picajoso** [iseulde/wp-front-end-editor#296]
The "+" symbol on that bar on the top of the page (covers a little part of my header or header image and it makes the preview look a little bit uglier) also allows only to insert an image or a gallery. 

The options for the previous versions of the plugin were more interesting and better presented too. The usability was IMHO also better.

That is also true with the new paragraph style that is available through that "¶" symbol. This was far easy to do on the previous version by selecting the text and aplying the style.

I also miss the "Add block" option when you left a new line empty. It was a nice way to insert new elements inline, more quick and coherent that going to the top bar to add image from there. Again, usability goes worse in this kind of interaction IMHO.

**Comment by iseulde** [comment]
I will add something like the new block thing again.

> That is also true with the new paragraph style that is available through that "¶" symbol. This was far easy to do on the previous version by selecting the text and aplying the style.

Do you mean the heading "styles"?

**Comment by picajoso** [comment]
Exactly. Heading styles were part of the normal formatting options once you selected text. That feels the right way to do it in my opinion.

**Comment by iseulde** [comment]
So the "problem" with heading is that they are not for selections. When you select some text it does not really make sense to show heading options since you can't convert that selection to a heading, only the block. But let's first try to look at the other issues.

I'll add the inline block toolbar again and try to move the publish toolbar to the bottom.

**Comment by picajoso** [comment]
Correct. When I'm writing I do know when I want to convert a block into a heading, so I actually write that sentence and press Enter to start writing another paragraph/block. That sentence is always a block itself, of course, so the old mechanic worked nicely for me. Thanks Iseulde

**Comment by iseulde** [comment]
Okay I've changed some things. The toolbar is now on the bottom, similar to 1.x. There is now a toolbar for empty lines (only media but will be extendible). The insert button in the main toolbar will stay as you need to be able to insert stuff elsewhere. For now I'll keep the paragraph button, but have some ideas to move it inline and will consider it. I hope the changes make it a bit better for now. :)

**Comment by iseulde** [comment]
More changes: I've moved the headings etc. inline again, but with an extra step. Now there's a button to select the whole block you're in, or multiple blocks. From there you can convert to headings, blockquote and lists. Maybe this is a bit annoying if you liked the flow with one click less, but this is to get a good visual idea of what's happening. So if you select some text, you can format text with inline elements, if you select the whole block, you can apply block formatting.

I hope this helps! Please don't hesitate to give feedback! I'll close this for now to get a better overview of what's done.

**Comment by iseulde** [comment]
See 47e431f1830ed0828e1dc0537397ecda3f3f94b3
