### ISSUE TITLE
Embed code option on empty new line

### ISSUE THREAD

**Issue by picajoso** [iseulde/wp-front-end-editor#300]
I wonder if this could be another option too for the plugin. When I want to add some embed code -for example, to insert a YouTube video- I must exit de WP Frontend Editor, go to the standard WP Editor, then enable the raw text editor and paste the text there. It would be nice to be able to add it while I'm writing.

**Comment by iseulde** [comment]
Do you mean a shortcode `[embed]...[/embed]`? or pasting the URL? When I paste the URL of a video it creates an embed.

**Comment by picajoso** [comment]
Uops. Didn't know that, I see it works :) Thanks!

**Comment by iseulde** [comment]
Is there a way in the admin to add embeds that is not possible with the front-end editor? You can use the media library and insert from URL, paste a URL etc. It just won't convert I think if you manually type the URL or shortcode...

Closing for now then. :)

**Comment by picajoso** [comment]
I really didn't know about that feature, and I guess it works for other
video sites as well. However, what happens if I want to embed other things
(a tweet, a Slideshare presentation maybe, a polldaddy poll)?

**Comment by iseulde** [comment]
Tweets should be fine too. Other embeds depend on core support, see https://github.com/WordPress/WordPress/blob/master/wp-includes/class-oembed.php. I see they are all supported, so if there are any problems pasting those URLs please reopen. If you're looking for a button or something to insert them, I'll let you add custom buttons soon, but as you can see from the list of supported services it's a bit unrealistic to add buttons for all. Not sure how else we can let the user know that they can paste URLs...

**Comment by picajoso** [comment]
I didn't know it was possible to add URLs and it would embed the block
right away myself, so maybe this is a feature others don't know as well.
Anyway, I'll keep trying this feature, you're absolutely right: adding
buttons for everything is even absurd.
