### ISSUE TITLE
Undefined index: modified in /wp-content/plugins/wp-front-end-editor/class-fee.php on line 241

### ISSUE THREAD

**Issue by limestreet** [iseulde/wp-front-end-editor#301]
There is PHP Notice - probably when there was no previous autosave:
`Undefined index: modified in /wp-content/plugins/wp-front-end-editor/class-fee.php on line 241`

On line 241 there is:
`'autosave' => strtotime($rest_autosave['modified']) > strtotime($rest_post['modified']) ? $rest_autosave : null,`

to solve this issue I think it should be:

`'autosave' => isset($rest_autosave['modified']) && strtotime($rest_autosave['modified']) > strtotime($rest_post['modified']) ? $rest_autosave : null,`

**Comment by iseulde** [comment]
Thanks for the report!

**Comment by iseulde** [comment]
Fixed in ef751578adbc5b3366b7a950fe71621b8fe946ab

**Comment by iseulde** [comment]
2.2.1 is available to fix the issue https://wordpress.org/plugins/wp-front-end-editor/

**Comment by limestreet** [comment]
Thanks!
Really nice project - hope it'll land in core :)
