### ISSUE TITLE
Doesn't play nice with many modern themes?

### ISSUE THREAD

**Issue by bigkev1983** [iseulde/wp-front-end-editor#70]
Hi - I really like your plug-in and want to use it for our school web site, which uses the Honey theme.

Unfortunately, it's a bit hit-and-miss with our pages.

When I go to edit a page, the formatting bar at the top becomes empty, preventing me from making any changes at all. I've taken two screenshots - one to show the front-end and the other showing the code in the standard WordPress Editor so you can see what might be causing the problem. I suspect it has something to do with the [wrapper] short code tags that are used. However, most modern themes include this way of presenting pages so we could definitely do with fixing that up.

Page layout (showing broken Inline Editor bar at the top)
http://www.designdynamos.com/server/fpeditor-2.tiff

Code for the page in the Standard WordPress Editor
http://www.designdynamos.com/server/fpeditor-3.tiff

Is this something that can be fixed easily?

https://wordpress.org/plugins/wp-front-end-editor/

**Comment by iseulde** [comment]
Closing for now as the editor changed a lot. Feel free to reopen if there are still compatibility issues.
