### ISSUE TITLE
Thumbnail image upload mouseover disappears as text is added

### ISSUE THREAD

**Issue by christopheran** [iseulde/wp-front-end-editor#94]
hmm, not a very good title.... but here's what happens.

As content is added, the ability to click on the thumbnail to upload a featured image stops working.

Ugh, let me show you here: 

http://screencast-o-matic.com/watch/c21efXnBWm 

Happens in both Chrome and MSIE.

The way I have the single.php page set up, the image is in a div inside the div with the content, before the content, floated to the right. So I have: 

<div>
<div style="float:right;"><?php the_post_thumbnail(); ?></div>
<?php the_content(); ?>
</div>

if that matters - 

Chris

**Comment by iseulde** [comment]
Is this gone now? Seems like an edge case when the featured image is not a block.

**Comment by iseulde** [comment]
This area is gone, you can insert a featured image with the media modal via the (+) icon or image button.
