### ISSUE TITLE
How would I include a custom function into the Front End Editor?

### ISSUE THREAD

**Issue by nativeimaging** [iseulde/wp-front-end-editor#96]
I'm currently using <a href="http://wordpress.org/plugins/featured-video-plus/" target="_blank">Featured Video Plus</a> plugin with my theme, and I would love to be able to hook the Meta box they provide into the WP Front End Editor. Is there somewhere the WP FEE file I can look into to see how I can implement this feature? Currently, there is no way to add a video link into the Feature Image location, it only allows images. 

![screen shot 2014-06-07 at 11 20 32 am](https://cloud.githubusercontent.com/assets/4061533/3209062/51c8971e-ee57-11e3-9e61-05e864112534.png)

Another question I have is about adding a button to the edit bar for a plugin I'm developing for generating markup in the post content.

![screen shot 2014-06-07 at 11 22 25 am](https://cloud.githubusercontent.com/assets/4061533/3209075/236bf914-ee58-11e3-8ea3-a3bbb6f60ba6.png)

**Comment by iseulde** [comment]
I added some filters in 47e431f1830ed0828e1dc0537397ecda3f3f94b3 to add more buttons.
