### ISSUE TITLE
Cannot edit title

### ISSUE THREAD

**Issue by puntorosso** [iseulde/wp-front-end-editor#97]
The plugin won't allow editing the post title in some Genesis theme (including the pure Genesis Framework). 
Content and images are accessible without problem.

Tested with Genesis Framework and the child themes "Lifestyle" and "Metro".
It works perfect with the child theme "Modern Portfolio".

**Comment by iseulde** [comment]
Editor changed a lot, so closing. Feel free to reopen if it's still an issue.
